#!/bin/sh

# Find the fastest active mirrors from the archlinux live mirrorlist
curl -s "https://www.archlinux.org/mirrorlist/?country=all&protocol=https&use_mirror_status=on" | sed -e s/^#Server/Server/ -e /^#/d | rankmirrors -n 20 - > /etc/pacman.d/mirrorlist
