#!/bin/sh
#
# Error:
# No protocol specified
# Unable to init server: Could not connect: Connection refused
# (gedit:2284): Gtk-WARNING **: cannot open display: :0

# Fix:
# Add user to root(sudo GUI + terminal)
xhost +si:localuser:root
# [output] localuser:root being added to access control list

# Reset to default, user cannot run root(GUI) in terminal
# xhost -si:localuser:root
