# Inserts a blank line between shell prompts
add_newline = false

[aws]
symbol = "aws "

[azure]
symbol = "az "

[battery]
disabled = true

[buf]
symbol = "buf "

[c]
symbol = "c "

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[cmake]
symbol = "cmake "

[cobol]
symbol = "cbl "

[conda]
symbol = "conda "

[container]
symbol = ""

[crystal]
symbol = "cr "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[directory]
read_only = "!w"

[docker_context]
symbol = "dock "

[dotnet]
format = "via [$symbol($version)($tfm)]($style)"

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[erlang]
symbol = "erl "

[gcloud]
symbol = "gc "

[git_branch]
symbol = "git "

[git_commit]
tag_symbol = ""

[git_status]
ahead = "a"
behind = "b"
conflicted = "c"
deleted = "x"
diverged = "d"
modified = "m"
renamed = "r"
stashed = "s"
untracked = "u"

[golang]
symbol = "go "

[haskell]
symbol = "hs "

[helm]
symbol = "helm "

[java]
symbol = "java "

[jobs]
symbol = "*"

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[kubernetes]
symbol = "kube "

[lua]
symbol = "lua "

[memory_usage]
disabled = true

[hg_branch]
symbol = "hg "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[nodejs]
symbol = "node "

[ocaml]
symbol = "opam "

[openstack]
symbol = "os "

[package]
symbol = "p "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulu "

[python]
symbol = "py "

[rlang]
symbol = "r "

[red]
symbol = "red "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[shlvl]
symbol = "shlvl "

[singularity]
symbol = "sing "

[spack]
symbol = "spack "

[swift]
symbol = "swift "

[terraform]
symbol = "terra "

[vagrant]
symbol = "vag "

[vlang]
symbol = "v "

[zig]
symbol = "zig "
